name: Softbee
description: "Application to control and monitor the status of apiaries and hives."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  dio: ^5.3.3
  provider: ^6.1.1
  url_launcher: ^6.2.1
  local_auth: ^2.1.7
  flutter_local_notifications: ^16.1.0
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.6.1
  go_router: ^17.0.1
  google_fonts: ^7.0.2
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  either_dart: ^1.0.0
  lottie: ^2.7.0
  equatable: ^2.0.5
  flutter_animate: ^4.5.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0

  flutter_test:
    sdk: flutter
  mockito: ^5.4.3
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo.png
    - assets/animations/
    # - .env

